### ISSUE TITLE
lib2to3 ParseError with Python 3.5 unpacking syntax

### ISSUE THREAD

**Issue by The-Compiler** [pyga/ebb-lint#4]
Running flake8 + ebb-lint over this file with Python 3.5 syntax:

``` python
def foo(one, two):
    pass

foo(**{'one': 1}, two=2)
```

Gives me:

```
Traceback (most recent call last):
  File "./.venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/pycodestyle.py", line 1877, in check_files
    runner(path)
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/pycodestyle.py", line 1608, in check_all
    self.check_ast()
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/pycodestyle.py", line 1555, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/ebb_lint/flake8.py", line 273, in run
    tree, trailing_newline = parse_source(d, self.source)
  File "/home/florian/tmp/.venv/lib/python3.5/site-packages/ebb_lint/flake8.py", line 120, in parse_source
    return driver.parse_string(source), trailing_newline
  File "/usr/lib64/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib64/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib64/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=12, value=',', context=('', (4, 16))
```

Not sure whether support for that just isn't in lib2to3 yet, or if ebb-lint can do anything about this?

**Comment by habnabit** [comment]
Barf. This is why I'm working on replacing lib2to3 with something that uses
the real grammars instead of hacky crap. So, working on it.

**Comment by sigmavirus24** [comment]
@habnabit you'll probably be interested in [this issue](https://github.com/davidhalter/jedi/issues/630) then

**Comment by habnabit** [comment]
That is interesting. I'll post in that thread when I'm not mobile.
